blank_issues_enabled: false
contact_links:
  - name: Authenticate
    url: https://memanto.ai/contributor-onboard
    about: Complete the Memanto contributor onboarding to unlock commenting and contributing. Takes 30 seconds. We don't store anything outside of github.
